# 1.3 Matrices: Representing Transformations

Interactive notebook for the **How AI Works** course. Run each cell top to bottom (Shift+Enter). The text and explanations live in the lesson page.

In [ ]:
# Setup: install the one dependency this course uses.
%pip install numpy --quiet

In [ ]:
import numpy as np

# We can create a 3x3 matrix by passing a list of lists to np.array()
matrix = np.array([
    [1.0, 2.0, 3.0],
    [4.0, 5.0, 6.0],
    [7.0, 8.0, 9.0]
])

print("Our 3x3 Matrix looks like this:")
print(matrix)

# We can check the 'shape' of our matrix
print(f"\nThe shape of the matrix is: {matrix.shape}")

# Accessing an element: [row, column] (starting at index 0)
# Let's get the number 6 (row 1, column 2)
element = matrix[1, 2]
print(f"The element at row 1, column 2 is: {element}")

# We can also grab an entire row:
first_row = matrix[0]
print(f"The first row is: {first_row}")

## Exercises

**Exercise 1:** Create a 2x4 matrix (2 rows, 4 columns) and print its shape. Then access the element at row 0, column 3.

<details>
<summary>Show solution</summary>

```python
import numpy as np

matrix = np.array([
    [1.0, 2.0, 3.0, 4.0],
    [5.0, 6.0, 7.0, 8.0]
])

print(f"Matrix shape: {matrix.shape}")
element = matrix[0, 3]
print(f"Element at row 0, column 3: {element}")
```

Expected output:
```text
Matrix shape: (2, 4)
Element at row 0, column 3: 4.0
```

</details>

**Exercise 2:** Create an identity matrix (a matrix where the diagonal is 1 and all other elements are 0) of size 3x3 using NumPy. What is special about an identity matrix?

<details>
<summary>Show solution</summary>

```python
import numpy as np

identity_matrix = np.eye(3)
print("Identity matrix:")
print(identity_matrix)
```

Expected output:
```text
Identity matrix:
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
```

The identity matrix is special because when you multiply any vector by the identity matrix, you get the same vector back (it doesn't change it).

</details>

**Exercise 3:** Create a matrix that represents a simple "weight matrix" with 3 inputs and 2 outputs. What does this matrix look like, and why might it be used in a neural network?

<details>
<summary>Show solution</summary>

```python
import numpy as np

# A weight matrix for 3 inputs → 2 outputs
# Each row represents the weights for one output neuron
weight_matrix = np.array([
    [0.5, -0.3, 0.8],
    [0.2, 0.6, -0.1]
])

print("Weight matrix (3 inputs → 2 outputs):")
print(weight_matrix)
print(f"Shape: {weight_matrix.shape}")
```

Expected output:
```text
Weight matrix (3 inputs → 2 outputs):
[[ 0.5 -0.3  0.8]
 [ 0.2  0.6 -0.1]]
Shape: (2, 3)
```

This matrix transforms 3 input features into 2 output features. In a neural network, each element is a "weight" that determines how much each input contributes to each output.

</details>

---

**Up Next:** Now that we know what a matrix is, let's learn how it actually "acts" on a vector in [**1.4 Matrix-Vector Multiplication**](1.4-matrix-vector-multiplication.md).

*Try each exercise in a new cell below before opening the solution.*